# Generated by Django 5.1.1 on 2024-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=250)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('DataNascimento', models.DateField(blank=True, null=True)),
                ('CEP', models.CharField(blank=True, max_length=15, null=True)),
                ('UserId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
