# Generated by Django 5.1.1 on 2024-10-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contato', '0002_alter_contatos_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contatos',
            name='CategoriaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Categoria_id', to='Contato.categoria'),
            preserve_default=False,
        ),
    ]
