# Generated by Django 5.1.1 on 2024-10-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contato', '0004_rename_contatos_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='CategoriaId',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='UserId',
            new_name='User',
        ),
    ]
