# Generated by Django 5.1.1 on 2024-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contato', '0007_alter_contato_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='CEP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
